
GET http://localhost:8188/courts
###

GET http://localhost:8188/courts/6466a828c826294f0e9d895d

###

POST http://localhost:8188/courts
Content-Type: application/json

{
    "name":"Porter Park Court",
    "condition":"excellent",
    "color":"blue",
    "latitude": 43.8230392594719,
    "longitude": -111.79129592907756
}

### 
PUT http://localhost:8188/courts/6466a5faeabd076bf67e6f5a
Content-Type: application/json

{
    "name":"Porter Park Court",
    "condition":"excellent",
    "color":"blue",
    "latitude": 43.8230392594719 , 
    "longitude": -111.79129592907756
}
###
DELETE http://localhost:8188/courts/64540d0ecdca455c937f1ce4